# Generated by Django 3.2.8 on 2021-11-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20211118_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableleaves',
            name='compensation_leaves',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='no_of_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
