# Generated by Django 3.2.8 on 2021-11-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20211118_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
