# Generated by Django 3.2.8 on 2021-11-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leave_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='hod_rejected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='principal_rejected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
