# Generated by Django 3.2.8 on 2021-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20211120_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='hod_rejected',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='principal_rejected',
        ),
        migrations.AlterField(
            model_name='leave',
            name='hod_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='principal_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
