# Generated by Django 3.2.8 on 2021-11-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20211120_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='leave_category',
            new_name='category',
        ),
    ]
