# Generated by Django 3.2.8 on 2022-02-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220222_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='sex',
            new_name='gender',
        ),
    ]
