# Generated by Django 3.2.8 on 2021-10-23 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('WISTM', 'College Campus'), ('AU', 'AU'), ('Counselling Duty', 'Counselling Duty'), ('Admission work', 'Admission work'), ('On Duty', 'On Duty'), ('Permission', 'Permission'), ('Leave', 'Leave'), ('Other', 'Other')], max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
