# Generated by Django 3.2.8 on 2021-10-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='emp_id',
            new_name='employee',
        ),
    ]
