# Generated by Django 3.2.8 on 2021-10-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_emp_id_attendance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='other',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
